/**
 * @author 
 * @since 10/26/2016
 */

(function () {
    'use strict';

    angular
        .module('myApp')
        .service('BasicserviceJsService', BasicserviceJsService);

    /* @ngInject */
    function BasicserviceJsService ($log) {
        var service = {};

        /// Service Public API ///
        service.method = method;
        ///////////////

        return service;

        ///////////////

        function method() {
            // TODO autogenerated method stub...
        }

    }
})();
